# Config file for standard model but with Hu et al. fire PM2.5 estimates
# Only use 2000-2017 data, no imputation of SE indicators
# Probabilistic PCA deprivation index.
# bc_attr_fire_PM25_emis_100_2000km as output (bias-corrected estimate of local fire_PM25_hu).
# ^^scaled dependent variable -- units expressed in SDs relative to continent mean.
project:
  data_filepath: "/work/scratch-pw5/cho00/data/spatial/fire_pm_dep_paper_data/proc_data/df_af_annual_loc_tp_2000_2023.csv"
  model_save_dir: "/work/scratch-pw5/cho00/data/spatial/deprivation_pm_bhm"
  nat_bounds_filepath: "/work/scratch-pw5/cho00/data/spatial/nat_boundaries/WB_countries_Admin0_10m"

environment:
  cmdstan_path: "/home/users/cho00/miniconda3/envs/ppca/bin/cmdstan"
  proj_data: "/home/users/cho00/miniconda3/envs/ppca/share/proj"

mcmc:
  chains: 4
  iter: 15000
  warmup: 5000
  threads: 24
  adapt_delta: 0.95

priors:
  beta_sd: 10
  scale_dist: "cauchy"

data:
  se_indicators:
    - "edu_mean_years"
    - "imp_san_access_pct"
    - "log_GDP_pc"
    - "stunting_pct_u5"
    - "child_dep_pct"
  centre_year: true
  scale_PC1: true
  scale_y: true
  max_year: 2017

pca:
  method: "ppca"  # probabilistic PCA
  n_pcs: 5
  scale: true
  centre: true
  seed: 42
  pc1_positive_loadings: ["stunting_pct_u5", "child_dep_pct"]
  pc1_negative_loadings: ["edu_mean_years",
                          "imp_san_access_pct",
                          "log_GDP_pc"]

model:
  name: "original_model_hu"
  description: "Hu et al. fire PM2.5 estimates, 2000-2017"
  outcome: "bc_attr_fire_PM25_emis_100_2000km" # note that this has same name as before but INLA model was fitted to & bias-corrected w/ Hu data
  formula_rhs: >
      0 + Intercept + PC1 * urban_rural_cat + year +
        (1 + PC1 * urban_rural_cat + year | country)
